### USER registration
POST http://localhost:3333/api/v1/users/register
Content-Type: application/json

{
	"email": "rthyssen75@gmail.com",
	"password": "1234567"
}

### USER login
POST http://localhost:3333/api/v1/users/login
Content-Type: application/json

{
	"email": "rthyssen73@gmail.com",
	"password": "1234567"
}

